package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.sql.SQLException;

/**
 *
 * @author victo
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPessoal
     */
    /**
     * Creates new form Menu
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelSelecionarFoto = new javax.swing.JLabel();
        jButtonSelecionarFoto = new javax.swing.JButton();
        jLabelNomeC = new javax.swing.JLabel();
        jTextFieldNomeC = new javax.swing.JTextField();
        jLabelSaudeBem = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelTipoSaguinio = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldTipoSaguinio = new javax.swing.JTextField();

        setTitle("Cadastro");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 620, 10);

        jLabelSelecionarFoto.setText("Selecionar foto");
        jPanel1.add(jLabelSelecionarFoto);
        jLabelSelecionarFoto.setBounds(50, 50, 80, 20);

        jButtonSelecionarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jButtonSelecionarFoto.setFocusPainted(false);
        jButtonSelecionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarFotoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSelecionarFoto);
        jButtonSelecionarFoto.setBounds(140, 50, 80, 70);

        jLabelNomeC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomeC.setText("Nome Completo: ");
        jPanel1.add(jLabelNomeC);
        jLabelNomeC.setBounds(50, 190, 90, 20);

        jTextFieldNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNomeC);
        jTextFieldNomeC.setBounds(140, 190, 410, 20);

        jLabelSaudeBem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bem(redim).png"))); // NOI18N
        jPanel1.add(jLabelSaudeBem);
        jLabelSaudeBem.setBounds(350, 0, 250, 40);

        jLabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSenha.setText("Senha: ");
        jPanel1.add(jLabelSenha);
        jLabelSenha.setBounds(100, 160, 40, 20);

        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmail.setText("Email: ");
        jPanel1.add(jLabelEmail);
        jLabelEmail.setBounds(90, 130, 50, 20);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(140, 130, 410, 20);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(140, 160, 410, 20);

        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(140, 250, 410, 20);

        jLabelEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEndereco.setText("Endereço: ");
        jPanel1.add(jLabelEndereco);
        jLabelEndereco.setBounds(80, 280, 60, 20);

        jLabelCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCPF.setText("CPF: ");
        jPanel1.add(jLabelCPF);
        jLabelCPF.setBounds(110, 250, 30, 20);

        jLabelTipoSaguinio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTipoSaguinio.setText("Tipo Saguíneo: ");
        jPanel1.add(jLabelTipoSaguinio);
        jLabelTipoSaguinio.setBounds(270, 220, 80, 20);

        jLabelCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCelular.setText(" Telefone/Celular: ");
        jPanel1.add(jLabelCelular);
        jLabelCelular.setBounds(40, 310, 100, 20);

        jLabelSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSexo.setText("Sexo: ");
        jPanel1.add(jLabelSexo);
        jLabelSexo.setBounds(100, 220, 40, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 310, 410, 20);
        jPanel1.add(jTextFieldSexo);
        jTextFieldSexo.setBounds(140, 220, 120, 20);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setFocusPainted(false);
        jButtonSalvar.setFocusable(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(260, 360, 110, 22);

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(140, 280, 410, 20);

        jTextFieldTipoSaguinio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoSaguinioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTipoSaguinio);
        jTextFieldTipoSaguinio.setBounds(350, 220, 200, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 614, 436);

        setSize(new java.awt.Dimension(614, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSelecionarFotoActionPerformed

    private void jTextFieldNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        cadastraUsuario();
        TelaLogin janelaTelaLogin = new TelaLogin();
        janelaTelaLogin.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldTipoSaguinioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoSaguinioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoSaguinioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSelecionarFoto;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNomeC;
    private javax.swing.JLabel jLabelSaudeBem;
    private javax.swing.JLabel jLabelSelecionarFoto;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTipoSaguinio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNomeC;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JTextField jTextFieldTipoSaguinio;
    // End of variables declaration//GEN-END:variables

    private void cadastraUsuario() {
        String cpf, senha, nome, email, endereco, tipo_sanguineo, sexo, numero_emergencia;
        email = jTextFieldEmail.getText();
        senha = jPasswordFieldSenha.getText();
        nome = jTextFieldNomeC.getText();
        sexo = jTextFieldSexo.getText();
        cpf = jTextFieldCPF.getText();
        endereco = jTextFieldEndereco.getText();
        numero_emergencia = jTextField1.getText();
        tipo_sanguineo = jTextFieldTipoSaguinio.getText();
        UsuarioDTO UsuarioDTO = new UsuarioDTO(cpf, nome, endereco, tipo_sanguineo, sexo, numero_emergencia, email, senha);
        UsuarioDAO UsuarioDAO = new UsuarioDAO();
        UsuarioDAO.create(UsuarioDTO);
        limpaCampos();
    }

    private void limpaCampos() {
        jTextFieldEmail.setText("");
        jPasswordFieldSenha.setText("");
        jTextFieldNomeC.setText("");
        jTextFieldSexo.setText("");
        jTextFieldCPF.setText("");
        jTextFieldEndereco.setText("");
        jTextField1.setText("");
        jTextFieldTipoSaguinio.setText("");
    }
}
