package VIEW;

import DAO.ExerciciosDAO;
import DTO.ExerciciosDTO;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class Exercicios extends javax.swing.JFrame {

    private String cpf;

    /**
     * Creates new form Exercicio
     */
    public Exercicios() {
        initComponents();
        readTable();
    }

    public void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableExercicios.getModel();
        modelo.setNumRows(0);
        ExerciciosDAO edao = new ExerciciosDAO();
        for (ExerciciosDTO e : edao.read()) {
            modelo.addRow(new Object[]{
                e.getNomeExercicios(),
                e.getSerieExercicios(),
                e.getRepeticao_exercicio()
            });
        }
    }

    public Exercicios(String cpf) {
        initComponents();
        this.cpf = cpf;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSaudeBem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonCronometro = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelNomeDoExercício = new javax.swing.JLabel();
        jTextFieldNomeDoExercício = new javax.swing.JTextField();
        jTextFieldSerie = new javax.swing.JTextField();
        jTextFieldRepetição = new javax.swing.JTextField();
        jLabelSerie = new javax.swing.JLabel();
        jLabelRepetição = new javax.swing.JLabel();
        jToggleButtonCadastrar = new javax.swing.JToggleButton();
        jToggleButtonAtualizar = new javax.swing.JToggleButton();
        jToggleButtonExcluir = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExercicios = new javax.swing.JTable();

        setTitle("Exercícios");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabelSaudeBem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bem(redim).png"))); // NOI18N
        jPanel1.add(jLabelSaudeBem);
        jLabelSaudeBem.setBounds(550, 0, 250, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 90, 810, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 40, 810, 10);

        jButtonCronometro.setText("Cronometro ⏰");
        jButtonCronometro.setFocusPainted(false);
        jButtonCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCronometroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCronometro);
        jButtonCronometro.setBounds(300, 50, 190, 30);

        jButtonVoltar.setText("↩");
        jButtonVoltar.setBorderPainted(false);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.setFocusPainted(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar);
        jButtonVoltar.setBounds(0, 0, 60, 40);

        jLabelNomeDoExercício.setText("Nome do exercício");
        jPanel1.add(jLabelNomeDoExercício);
        jLabelNomeDoExercício.setBounds(20, 100, 200, 14);

        jTextFieldNomeDoExercício.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeDoExercícioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNomeDoExercício);
        jTextFieldNomeDoExercício.setBounds(20, 120, 200, 20);
        jPanel1.add(jTextFieldSerie);
        jTextFieldSerie.setBounds(230, 120, 200, 20);

        jTextFieldRepetição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRepetiçãoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRepetição);
        jTextFieldRepetição.setBounds(440, 120, 200, 20);

        jLabelSerie.setText("Serie");
        jPanel1.add(jLabelSerie);
        jLabelSerie.setBounds(230, 100, 200, 14);

        jLabelRepetição.setText("Repetição");
        jPanel1.add(jLabelRepetição);
        jLabelRepetição.setBounds(440, 100, 200, 14);

        jToggleButtonCadastrar.setText("Cadastrar");
        jToggleButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButtonCadastrar);
        jToggleButtonCadastrar.setBounds(670, 160, 105, 23);

        jToggleButtonAtualizar.setText("Atualizar");
        jToggleButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButtonAtualizar);
        jToggleButtonAtualizar.setBounds(670, 200, 105, 23);

        jToggleButtonExcluir.setText("Excluir");
        jToggleButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButtonExcluir);
        jToggleButtonExcluir.setBounds(670, 240, 105, 23);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableExercicios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableExercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do exercício", "Serie", "Repetição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableExercicios.setColumnSelectionAllowed(true);
        jTableExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExerciciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExercicios);
        jTableExercicios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTableExercicios.getColumnModel().getColumnCount() > 0) {
            jTableExercicios.getColumnModel().getColumn(0).setResizable(false);
            jTableExercicios.getColumnModel().getColumn(1).setResizable(false);
            jTableExercicios.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 620, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 320);

        setSize(new java.awt.Dimension(814, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Menu janelaMenu = new Menu(this.cpf);
        janelaMenu.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCronometroActionPerformed
        Cronometro janelaCronometro = new Cronometro(this.cpf);
        janelaCronometro.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCronometroActionPerformed

    private void jToggleButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAtualizarActionPerformed
        atualizaTabela();
        readTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAtualizarActionPerformed

    private void jTextFieldRepetiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRepetiçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRepetiçãoActionPerformed

    private void jTextFieldNomeDoExercícioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeDoExercícioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeDoExercícioActionPerformed

    private void jToggleButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExcluirActionPerformed
        excluir();
        readTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonExcluirActionPerformed

    private void jToggleButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastrarActionPerformed
        cadastrar();
        readTable();
    }//GEN-LAST:event_jToggleButtonCadastrarActionPerformed

    private void jTableExerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExerciciosMouseClicked
        if (jTableExercicios.getSelectedRow() != -1) {
            jTextFieldNomeDoExercício.setText(jTableExercicios.getValueAt(jTableExercicios.getSelectedRow(), 0).toString());
            jTextFieldSerie.setText(jTableExercicios.getValueAt(jTableExercicios.getSelectedRow(), 1).toString());
            jTextFieldRepetição.setText(jTableExercicios.getValueAt(jTableExercicios.getSelectedRow(), 2).toString());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jTableExerciciosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCronometro;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelNomeDoExercício;
    private javax.swing.JLabel jLabelRepetição;
    private javax.swing.JLabel jLabelSaudeBem;
    private javax.swing.JLabel jLabelSerie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableExercicios;
    private javax.swing.JTextField jTextFieldNomeDoExercício;
    private javax.swing.JTextField jTextFieldRepetição;
    private javax.swing.JTextField jTextFieldSerie;
    private javax.swing.JToggleButton jToggleButtonAtualizar;
    private javax.swing.JToggleButton jToggleButtonCadastrar;
    private javax.swing.JToggleButton jToggleButtonExcluir;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {
        jTableExercicios.getSelectedRow();
        ExerciciosDTO exer = new ExerciciosDTO();
        ExerciciosDAO dao = new ExerciciosDAO();
        exer.setNomeExercicioso(jTextFieldNomeDoExercício.getText());
        exer.setSerieExercicios(jTextFieldSerie.getText());
        exer.setRepeticao_exercicio(jTextFieldRepetição.getText());
        dao.create(exer);
        jTextFieldNomeDoExercício.setText("");
        jTextFieldSerie.setText("");
        jTextFieldRepetição.setText("");
        readTable();
    }

    private void atualizaTabela() {
        jTableExercicios.getSelectedRow();
        if (jTableExercicios.getSelectedRow() != -1) {
            ExerciciosDTO exer = new ExerciciosDTO();
            ExerciciosDAO dao = new ExerciciosDAO();
            exer.setNomeExercicioso(jTableExercicios.getValueAt(jTableExercicios.getSelectedRow(), 0).toString());
            exer.setSerieExercicios(jTextFieldSerie.getText());
            exer.setRepeticao_exercicio(jTextFieldRepetição.getText());
            dao.update(exer);
            jTextFieldNomeDoExercício.setText("");
            jTextFieldSerie.setText("");
            jTextFieldRepetição.setText("");
            readTable();
        }
    }

    private void excluir() {
        jTableExercicios.getSelectedRow();
        if (jTableExercicios.getSelectedRow() != -1) {
            ExerciciosDTO exer = new ExerciciosDTO();
            ExerciciosDAO dao = new ExerciciosDAO();
            exer.setNomeExercicioso(jTableExercicios.getValueAt(jTableExercicios.getSelectedRow(), 0).toString());
            dao.delete(exer);
            jTextFieldNomeDoExercício.setText("");
            jTextFieldSerie.setText("");
            jTextFieldRepetição.setText("");
            readTable();
        }
    }
}
