package VIEW;

/**
 *
 * @author victo
 */
public class Menu extends javax.swing.JFrame {

    private String cpf;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    public Menu(String cpf) {
        initComponents();
        this.cpf = cpf;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonconsumo = new javax.swing.JButton();
        jButtonPeso = new javax.swing.JButton();
        jButtonExercicios = new javax.swing.JButton();
        jButtonPerfil = new javax.swing.JButton();
        jButtonAlimentacao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1Sair = new javax.swing.JButton();

        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setFocusable(false);
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bem(redim).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 0, 250, 40);

        jButtonconsumo.setText("Consumo de água");
        jButtonconsumo.setFocusable(false);
        jButtonconsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsumoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonconsumo);
        jButtonconsumo.setBounds(30, 180, 260, 23);

        jButtonPeso.setText("Controle de peso");
        jButtonPeso.setFocusable(false);
        jButtonPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPeso);
        jButtonPeso.setBounds(320, 180, 260, 23);

        jButtonExercicios.setText("Exercícios");
        jButtonExercicios.setFocusable(false);
        jButtonExercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExerciciosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExercicios);
        jButtonExercicios.setBounds(320, 140, 260, 23);

        jButtonPerfil.setText("Perfil");
        jButtonPerfil.setFocusPainted(false);
        jButtonPerfil.setFocusable(false);
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPerfil);
        jButtonPerfil.setBounds(90, 70, 90, 22);

        jButtonAlimentacao.setText("Alimentação");
        jButtonAlimentacao.setFocusPainted(false);
        jButtonAlimentacao.setFocusable(false);
        jButtonAlimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlimentacaoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlimentacao);
        jButtonAlimentacao.setBounds(30, 140, 260, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 50, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 620, 10);

        jButton1Sair.setText("Sair");
        jButton1Sair.setFocusPainted(false);
        jButton1Sair.setFocusable(false);
        jButton1Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SairActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Sair);
        jButton1Sair.setBounds(260, 260, 90, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 310);

        setSize(new java.awt.Dimension(614, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        Perfil janelaCadastroPessoal = new Perfil(this.cpf);
        janelaCadastroPessoal.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jButtonAlimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlimentacaoActionPerformed
        Alimentacao janelaAlimentacao = new Alimentacao(this.cpf);
        janelaAlimentacao.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlimentacaoActionPerformed

    private void jButtonExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExerciciosActionPerformed
        Exercicios janelaExercicios = new Exercicios(this.cpf);
        janelaExercicios.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExerciciosActionPerformed

    private void jButtonconsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsumoActionPerformed
        ConsumoDeAgua janelaConsumoDeAgua = new ConsumoDeAgua(this.cpf);
        janelaConsumoDeAgua.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonconsumoActionPerformed

    private void jButtonPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesoActionPerformed
        ControleDePeso janelaControleDePeso = new ControleDePeso(this.cpf);
        janelaControleDePeso.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesoActionPerformed

    private void jButton1SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SairActionPerformed
        TelaLogin janelaTelaLogin = new TelaLogin();
        janelaTelaLogin.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Sair;
    private javax.swing.JButton jButtonAlimentacao;
    private javax.swing.JButton jButtonExercicios;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JButton jButtonPeso;
    private javax.swing.JButton jButtonconsumo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
