package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public final class Perfil extends javax.swing.JFrame {

    private String cpf;
    private Frame jFrame;

    public Perfil() {
        initComponents();
    }

    public Perfil(String cpf) {
        initComponents();
        this.cpf = cpf;
        this.carregaUsuario();
        jTextFieldEmail.enable(false);
        jPasswordFieldSenha.enable(false);
        jTextFieldNomeC.enable(false);
        jTextFieldSexo.enable(false);
        jTextFieldTipoSaguinio.enable(false);
        jTextFieldCPF.enable(false);
        jTextFieldEndereco.enable(false);
        jTextFieldCelular.enable(false);
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldSexo = new javax.swing.JTextField();
        jButtonSelecionarFoto = new javax.swing.JButton();
        jTextFieldNomeC = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelSaudeBem = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldTipoSaguinio = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelNomeC = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelTipoSaguinio = new javax.swing.JLabel();
        jButtonSalvar1 = new javax.swing.JButton();
        jToggleButtonEditar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(140, 250, 410, 20);

        jTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCelularActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCelular);
        jTextFieldCelular.setBounds(140, 310, 410, 20);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(140, 130, 410, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 620, 10);
        jPanel1.add(jTextFieldSexo);
        jTextFieldSexo.setBounds(140, 220, 120, 20);

        jButtonSelecionarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jButtonSelecionarFoto.setFocusPainted(false);
        jButtonSelecionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarFotoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSelecionarFoto);
        jButtonSelecionarFoto.setBounds(270, 50, 80, 70);

        jTextFieldNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNomeC);
        jTextFieldNomeC.setBounds(140, 190, 410, 20);

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(140, 280, 410, 20);

        jLabelSaudeBem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bem(redim).png"))); // NOI18N
        jPanel1.add(jLabelSaudeBem);
        jLabelSaudeBem.setBounds(350, 0, 250, 40);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(140, 160, 410, 20);

        jTextFieldTipoSaguinio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoSaguinioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTipoSaguinio);
        jTextFieldTipoSaguinio.setBounds(350, 220, 200, 20);

        jButton2.setText("↩");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 60, 40);

        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmail.setText("Email: ");
        jPanel1.add(jLabelEmail);
        jLabelEmail.setBounds(90, 130, 50, 20);

        jLabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSenha.setText("Senha: ");
        jPanel1.add(jLabelSenha);
        jLabelSenha.setBounds(100, 160, 40, 20);

        jLabelNomeC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomeC.setText("Nome Completo: ");
        jPanel1.add(jLabelNomeC);
        jLabelNomeC.setBounds(50, 190, 90, 20);

        jLabelSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSexo.setText("Sexo: ");
        jPanel1.add(jLabelSexo);
        jLabelSexo.setBounds(100, 220, 40, 20);

        jLabelCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCPF.setText("CPF: ");
        jPanel1.add(jLabelCPF);
        jLabelCPF.setBounds(110, 250, 30, 20);

        jLabelEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEndereco.setText("Endereço: ");
        jPanel1.add(jLabelEndereco);
        jLabelEndereco.setBounds(80, 280, 60, 20);

        jLabelCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCelular.setText(" Telefone/Celular: ");
        jPanel1.add(jLabelCelular);
        jLabelCelular.setBounds(40, 310, 100, 20);

        jLabelTipoSaguinio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTipoSaguinio.setText("Tipo Saguíneo: ");
        jPanel1.add(jLabelTipoSaguinio);
        jLabelTipoSaguinio.setBounds(270, 220, 80, 20);

        jButtonSalvar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSalvar1.setText("Salvar");
        jButtonSalvar1.setFocusPainted(false);
        jButtonSalvar1.setFocusable(false);
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar1);
        jButtonSalvar1.setBounds(440, 360, 110, 30);

        jToggleButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButtonEditar.setText("Editar");
        jToggleButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButtonEditar);
        jToggleButtonEditar.setBounds(320, 360, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Excluir conta");
        jButton1.setAutoscrolls(true);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 360, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 430);

        setSize(new java.awt.Dimension(614, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCelularActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonSelecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSelecionarFotoActionPerformed

    private void jTextFieldNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldTipoSaguinioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoSaguinioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoSaguinioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu janelaMenu = new Menu(this.cpf);
        janelaMenu.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        editaUsuario();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed

    private void jToggleButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEditarActionPerformed
        jTextFieldEmail.enable(true);
        jPasswordFieldSenha.enable(true);
        jTextFieldNomeC.enable(true);
        jTextFieldSexo.enable(true);
        jTextFieldTipoSaguinio.enable(true);
        jTextFieldCPF.enable(true);
        jTextFieldEndereco.enable(true);
        jTextFieldCelular.enable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        excluirconta();
        TelaLogin janelaTelaLogin = new TelaLogin();
        janelaTelaLogin.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JButton jButtonSelecionarFoto;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNomeC;
    private javax.swing.JLabel jLabelSaudeBem;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTipoSaguinio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNomeC;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JTextField jTextFieldTipoSaguinio;
    private javax.swing.JToggleButton jToggleButtonEditar;
    // End of variables declaration//GEN-END:variables

    public void carregaUsuario() {
        UsuarioDAO userDAO = new UsuarioDAO();
        UsuarioDTO userDTO = new UsuarioDTO();
        try {
            userDTO.setCpf(this.cpf);
            ResultSet rs;
            rs = userDAO.loadUser(userDTO);
            if (rs.next()) {
                userDTO.setEmail(rs.getString("email"));
                userDTO.setSenha(rs.getString("senha"));
                userDTO.setNome(rs.getString("nome"));
                userDTO.setSexo(rs.getString("sexo"));
                userDTO.setCpf(rs.getString("cpf"));
                userDTO.setEndereco(rs.getString("endereco"));
                userDTO.setNumero_emergencia(rs.getString("numero_emergencia"));
                userDTO.setTipo_sanguineo(rs.getString("tipo_sanguineo"));
                jTextFieldCPF.setText(userDTO.getCpf());
                jTextFieldEmail.setText(userDTO.getEmail());
                jPasswordFieldSenha.setText(userDTO.getSenha());
                jTextFieldNomeC.setText(userDTO.getNome());
                jTextFieldSexo.setText(userDTO.getSexo());
                jTextFieldEndereco.setText(userDTO.getEndereco());
                jTextFieldCelular.setText(userDTO.getNumero_emergencia());
                jTextFieldTipoSaguinio.setText(userDTO.getTipo_sanguineo());
            }
        }
        catch (SQLException ex) {
            System.out.println("erro carregaUsuario() " + ex);
        }
    }

    private void editaUsuario() {
        String cpf, senha, nome, email, endereco, tipo_sanguineo, sexo, numero_emergencia;
        email = jTextFieldEmail.getText();
        senha = jPasswordFieldSenha.getText();
        nome = jTextFieldNomeC.getText();
        sexo = jTextFieldSexo.getText();
        cpf = jTextFieldCPF.getText();
        endereco = jTextFieldEndereco.getText();
        numero_emergencia = jTextFieldCelular.getText();
        tipo_sanguineo = jTextFieldTipoSaguinio.getText();
        UsuarioDTO UsuarioDTO = new UsuarioDTO(cpf, nome, endereco, tipo_sanguineo, sexo, numero_emergencia, email, senha);
        UsuarioDAO UsuarioDAO = new UsuarioDAO();
        UsuarioDAO.update(UsuarioDTO);
        System.out.println("Atualizado com sucesso! ");
    }

    public void excluirconta() {
        String cpf, senha, nome, email, endereco, tipo_sanguineo, sexo, numero_emergencia;
        email = jTextFieldEmail.getText();
        senha = jPasswordFieldSenha.getText();
        nome = jTextFieldNomeC.getText();
        sexo = jTextFieldSexo.getText();
        cpf = jTextFieldCPF.getText();
        endereco = jTextFieldEndereco.getText();
        numero_emergencia = jTextFieldCelular.getText();
        tipo_sanguineo = jTextFieldTipoSaguinio.getText();
        UsuarioDTO UsuarioDTO = new UsuarioDTO(cpf, nome, endereco, tipo_sanguineo, sexo, numero_emergencia, email, senha);
        UsuarioDAO UsuarioDAO = new UsuarioDAO();
        UsuarioDAO.delete(UsuarioDTO);
        JOptionPane.showMessageDialog(null, "Conta excluida com sucesso");
    }
}
